version: "3.8"

services:
  astro:
    container_name: astro
    image: astro
    build:
      context: .
      dockerfile: docker/Dockerfile
    platform: linux/amd64
    restart: always
    ports:
      - "8080:8080"
